# Generated by Django 4.2.11 on 2024-10-07 09:49

from django.db import migrations, models
import django.db.models.deletion
import galerie.models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_user_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='save_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='uploadimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=galerie.models.user_upload_path)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerie.folder')),
            ],
        ),
    ]
