# Generated by Django 4.2.11 on 2024-10-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0003_folder_save_image_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
