# Generated by Django 4.2.11 on 2024-10-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0004_alter_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
    ]
