# Generated by Django 4.2.11 on 2024-10-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0005_abc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='folder',
            field=models.CharField(max_length=20),
        ),
    ]
