# Generated by Django 4.2.11 on 2024-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0006_alter_uploadimage_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corbeille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='corbeille/')),
            ],
        ),
    ]
