# Generated by Django 4.2.11 on 2024-10-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0008_folder_user_alter_corbeille_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='corbeille',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galerie.folder'),
        ),
    ]
