# Generated by Django 4.2.11 on 2024-10-09 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0009_corbeille_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='corbeille',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
